# for testing against a production-like environment in our CI

services:
  client:
    build:
      context: ./apps/desktop
      target: production
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"

  api:
    build:
      context: ./apps/api
      target: production
    env_file:
      - .env

  postgres:
    restart: unless-stopped