services:
  client:
    restart: unless-stopped
    build: ./frontend
    ports:
      - "5100:5100"
    # lets us hot reload with vite
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /client
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  api:
    container_name: pantryapi
    restart: unless-stopped
    build: ./backend
    ports:
      - "4100:4100"
    
    ## theoretically this helps argon2/bcrypt work in docker, but also it removes updates and requires a rebuild to see changes
    #volumes:
    #  - .:/backend
    #  - /backend/node_modules
    
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /api
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mongo
      - postgres
  mongo:
    container_name: pantrydb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    restart: unless-stopped
    volumes:
      - appdata:/data/pantrydb
    ports:
      - "27117:27117"
    command: --port 27117 ## Docker containers in same compose file still see mongo as 27017 otherwise

  postgres:
    image: postgres
    container_name: pantrypg
    volumes:
      - appdata:/data/pantrypg
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "4321:4321"


volumes:
  appdata:
