services:
  client:
    build:
      context: ./frontend
      target: production
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:80"

  api:
    build:
      context: ./backend
      target: production
    env_file:
      - .env

  postgres:
    restart: unless-stopped