services:
  client:
    container_name: pantryclient
    restart: unless-stopped
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      api:
        condition: service_healthy
    # lets us hot reload with vite
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /client
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json


  api:
    container_name: pantryapi
    restart: unless-stopped
    build: ./backend
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${SERVER_PORT}/health || exit 1"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 10      
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /api
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:18.1-alpine
    container_name: pantrypg
    volumes:
      - db_data:/data/pantrypg
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    # command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 3s
      retries: 10

  e2e:
    image: cypress/included:14.0.0
    build: ./frontend/cypress/e2e
    container_name: cypress
    depends_on:
      api:
        condition: service_healthy    
    environment:
      - CYPRESS_baseUrl=http://client:${CLIENT_PORT}
    command: npx cypress run
    volumes:
      - ./frontend/cypress:/app/cypress
      - ./frontend/cypress.config.js:/app/cypress.config.js


volumes:
  db_data: {}