name: Testing Cypress

on:
  push:
    branches:
      - stage

jobs:
  cypress-test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:18.1
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          # I really want to use ${{ secrets.POSTGRES_PORT }} here and it won't let me. 5432 it is, then
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node
          uses: actions/setup-node@v6
          with:
            node-version: "24"

        - name: Install server dependencies
          working-directory: ./backend
          run: npm install

        - name: Start project server
          working-directory: ./backend
          # bash >> npm run dev &
          # powershell >> Start-Process npm run dev
          # runs command in background to allow continued shell command use
          run: |
            echo "Starting server from /backend folder"
            echo "${{secrets.A_WHOLE_ENV_FILE }}" > .env
            npm run dev &
            echo "Waiting for server to be ready"
            while ! curl -sf http://localhost:${{ secrets.SERVER_PORT }}/health; do
              echo "Waiting for server and DB"
              sleep 5
            done

        - name: run Cypress
          uses: cypress-io/github-action@v6
          with:
            working-directory: ./frontend 
            start: npm run dev
            wait-on: 'http://localhost:${{ secrets.CLIENT_PORT }}, http://localhost:${{ secrets.SERVER_PORT }}/health'
          env:
              CYPRESS_baseUrl: http://localhost:${{ secrets.CLIENT_PORT }}
              CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
              SERVER_PORT: ${{ secrets.SERVER_PORT }}
  
