name: CI/CD Pipeline

on:
  push:
    branches:
      - stage

jobs:
  cypress-test:
    runs-on: ubuntu-24.04


    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: run Cypress
          uses: cypress-io/github-action@v6
          with:
            working-directory: ./frontend 
            start: npm run dev
            wait-on: 'http://localhost:${{ secrets.CLIENT_PORT }}, http://localhost:${{ secrets.SERVER_PORT }}/health'
            wait-on-timeout: 60
          env:
              CYPRESS_baseUrl: http://localhost:${{ secrets.CLIENT_PORT }}
              CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
              SERVER_PORT: ${{ secrets.SERVER_PORT }}
  
